frontend/urls.py
from django.conf.urls import include  
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('terms-of-use', views.terms_of_use, name='terms-of-use'),
    path('privacy-policy', views.privacy_policy, name='privacy-policy'),
    path('storage/', views.storage, name='storage'),
    path('storage/add/', views.storage_add, name='storage_add'),
    path('storage/<int:pk>/update/', views.storage_update, name='storage_update'),
    path('storage/<int:pk>/delete/', views.storage_delete, name='storage_delete'),
    path('compute/', views.compute, name='compute'),
    path('compute/add/', views.compute_add, name='compute_add'),
    path('compute/<int:pk>/update/', views.compute_update, name='compute_update'),
    path('compute/<int:pk>/delete/', views.compute_delete, name='compute_delete'),
    path('jobs/', views.jobs, name='jobs'),
    path('jobs/actions/', views.job_actions, name='job_actions'),
    path('jobs/create/', views.job_create, name='job_create'),
    path('jobs/<int:pk>/delete/', views.jobs_delete, name='job_delete'),
    path('jobs/delete/', views.jobs_delete, name='jobs_delete'),
    path('jobs/<int:pk>', views.job_describe, name='job_describe'),
    path('jobs/<int:pk>/logs/', views.job_logs, name='job_logs'),
    path('jobs/<int:pk>/json/', views.job_json, name='job_json'),
    path('jobs/<int:pk>/usage/', views.job_usage, name='job_usage'),
    path('workflows/', views.workflows, name='workflows'),
    path('workflows/actions/', views.workflow_actions, name='workflow_actions'),
    path('workflows/<int:pk>/delete/', views.workflows_delete, name='workflow_delete'),
    path('workflows/delete/', views.workflows_delete, name='workflows_delete'),
    path('workflows/<int:pk>', views.workflow, name='workflow'),
    path('user/usage/', views.user_usage, name='user-usage'),
    path('user/create-token/', views.create_token, name='create-token'),
    path('user/revoke-token/', views.revoke_token, name='revoke-token'),
    path('refresh/authorise', views.refresh_authorise, name='refresh_authorise'),
    path('refresh/callback', views.refresh_callback, name='refresh_callback'),
    path('api/', include('frontend.api.urls')),
]

prominence/urls.py
from django.contrib import admin
from django.urls import re_path, path, include
from django.views.generic.base import RedirectView
from allauth.account.views import logout

urlpatterns = [
    re_path(r'^accounts/email/', RedirectView.as_view(url='/', permanent=False)),
    re_path(r'^accounts/password/', RedirectView.as_view(url='/', permanent=False)),
    re_path(r'^accounts/inactive/', RedirectView.as_view(url='/', permanent=False)),
    re_path(r'^accounts/confirm-email/', RedirectView.as_view(url='/', permanent=False)),
    re_path(r'^login/', RedirectView.as_view(url='/', permanent=False)),
    re_path(r'^signup/', RedirectView.as_view(url='/', permanent=False)),
    path('logout/', logout, name='account_logout'),
    path('accounts/egicheckin/', include('egicheckin.urls')),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
]

frontend/models.py
from django.conf import settings
from django.db import models

class Workflow(models.Model):
    WORKFLOW_STATUSES = (
        (0, 'pending'),
        (1, 'pending'),
        (2, 'running'),
        (3, 'completed'),
        (4, 'deleted'),
        (5, 'failed'),
        (6, 'killed'),
        (7, 'unknown'),
    )

    WORKFLOW_STATUS_REASONS = (
        (0, ''),
        (1, 'Workflow deleted by user'),
        (2, 'One or more jobs failed'),
    )

    backend_id = models.PositiveIntegerField(db_index=True, unique=True, blank=True, null=True, default=None)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="workflows", null=True)
    name = models.CharField(max_length=512)
    status = models.PositiveSmallIntegerField(choices=WORKFLOW_STATUSES, default=0)
    status_reason = models.PositiveSmallIntegerField(choices=WORKFLOW_STATUS_REASONS, default=0)
    updated = models.BooleanField(default=False)
    in_queue = models.BooleanField(default=False)
    created = models.PositiveIntegerField(default=0)
    time_start = models.PositiveIntegerField(default=0)
    time_end = models.PositiveIntegerField(default=0)
    sandbox = models.CharField(max_length=100)
    uuid = models.CharField(max_length=36)
    jobs_total = models.PositiveIntegerField(default=0)
    jobs_done = models.PositiveIntegerField(default=0)
    jobs_failed = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

class Job(models.Model):
    JOB_STATUSES = (
        (0, 'pending'),
        (1, 'pending'),
        (2, 'running'),
        (3, 'completed'),
        (4, 'deleted'),
        (5, 'failed'),
        (6, 'killed'),
        (7, 'unknown'),
    )

    JOB_STATUS_REASONS = (
        (0, ''),
        (1, 'Creating infrastructure to run job'),
        (2, 'No matching resources'),
        (3, 'No matching resources currently available'),
        (4, 'Deployment failed'),
        (5, 'Unable to mount storage volume'),
        (6, 'Artifact download failed'),
        (7, 'Artifact uncompress failed'),
        (8, 'Stageout failed due to no such file or directory'),
        (9, 'Unable to stageout output to object storage'),
        (10, 'Container image pull failed'),
        (11, 'Job part of a workflow which was deleted by user'),
        (12, 'Walltime limit exceeded'),
        (13, 'Maximum time queued was exceeded'),
        (14, 'Executable exited with a non-zero exit code'),
        (15, 'Infrastructure took too long to be deployed'),
        (16, 'Job deleted by user'),
        (17, 'Quota exceeded'),
        (18, 'Required VM image not found'),
        (19, 'Infrastructure failed before job completed')
    )

    backend_id = models.PositiveIntegerField(db_index=True, unique=True, blank=True, null=True, default=None)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="jobs", null=True)
    name = models.CharField(max_length=512)
    status = models.PositiveSmallIntegerField(choices=JOB_STATUSES, default=0)
    status_reason = models.PositiveSmallIntegerField(choices=JOB_STATUS_REASONS, default=0)
    updated = models.BooleanField(default=False)
    in_queue = models.BooleanField(default=False)
    created = models.PositiveIntegerField(default=0)
    time_start = models.PositiveIntegerField(default=0)
    time_end = models.PositiveIntegerField(default=0)
    site = models.CharField(max_length=32, blank=True)
    sandbox = models.CharField(max_length=512)
    uuid = models.CharField(max_length=36)
    image = models.CharField(max_length=512)
    command = models.CharField(max_length=1024)
    request_cpus = models.PositiveSmallIntegerField(default=1)
    request_memory = models.PositiveSmallIntegerField(default=1)
    request_disk = models.PositiveSmallIntegerField(default=10)
    request_nodes = models.PositiveSmallIntegerField(default=1)
    workflow = models.ForeignKey(Workflow, on_delete=models.CASCADE, blank=True, null=True, related_name="jobs")
    #workflow_node_name = models.CharField(max_length=512)
    #workflow_node_factory_id = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

class JobLabel(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE, db_index=True, related_name="labels")
    key = models.CharField(max_length=512)
    value = models.CharField(max_length=512)

    def __str__(self):
        return self.name

class WorkflowLabel(models.Model):
    workflow = models.ForeignKey(Workflow, on_delete=models.CASCADE, db_index=True, related_name="labels")
    key = models.CharField(max_length=512)
    value = models.CharField(max_length=512)

    def __str__(self):
        return self.name

class Storage(models.Model):
    WEBDAV = 1
    ONEDATA = 2
    STORAGE_TYPES = (
        (WEBDAV, 'WebDAV'),
        (ONEDATA, 'OneData'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="storage_systems", null=True)
    name = models.CharField(max_length=120)
    hostname = models.CharField(max_length=120)
    username = models.CharField(max_length=120, blank=True)
    password = models.CharField(max_length=250, blank=True)
    token = models.CharField(max_length=250, blank=True)
    space = models.CharField(max_length=120, blank=True)
    storage_type = models.PositiveSmallIntegerField(choices=STORAGE_TYPES, default=2, blank=False)

    def __str__(self):
        return self.name

class Compute(models.Model):
    RESOURCE_TYPES = (
        (1, 'OpenStack'),
        (2, 'GCP'),
        (3, 'Azure'),
        (4, 'AWS'),
        (5, 'Kubernetes')
    )

    AUTH_VERSIONS = (
        (1, '2.0_password'),
        (2, '3.x_password'),
        (3, '3.x_oidc_access_token')
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="resources", null=True)
    resource_type = models.PositiveSmallIntegerField(choices=RESOURCE_TYPES, default=1, blank=False)
    name = models.CharField(max_length=120)
    image_name = models.CharField(max_length=120, blank=True)

    ost_host = models.CharField(max_length=120, blank=True)
    ost_username = models.CharField(max_length=120, blank=True)
    ost_password = models.CharField(max_length=250, blank=True)
    ost_tenant = models.CharField(max_length=120, blank=True)
    ost_domain = models.CharField(max_length=120, blank=True)
    ost_auth_version = models.PositiveSmallIntegerField(choices=AUTH_VERSIONS, default=2, blank=False)
    ost_service_region = models.CharField(max_length=120, blank=True)
    ost_tenant_domain_id = models.CharField(max_length=120, blank=True)

    gcp_sa_email = models.CharField(max_length=500, blank=True)
    gcp_sa_private_key = models.CharField(max_length=5000, blank=True)
    gcp_project = models.CharField(max_length=120, blank=True)
    gcp_regions = models.CharField(max_length=120, blank=True)

    def __str__(self):
        return self.name

frontend/views/compute.py
import logging

from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required

from frontend.models import Compute
from frontend.forms import ComputeForm

# Get an instance of a logger
logger = logging.getLogger(__name__)

@login_required
def compute(request):
    compute_list = request.user.resources.all()
    return render(request, 'clouds.html', {'resources': compute_list})

@login_required
def compute_add(request):
    if request.method == 'POST':
        form = ComputeForm(request.POST)
        if form.is_valid():
            compute = form.save(commit=False)
            compute.user = request.user
            compute.save()
        return redirect('/compute')
    else:
        form = ComputeForm()

    return render(request, 'compute-add.html', {'form': form})

@login_required
def compute_update(request, pk):
    compute = get_object_or_404(Compute, user=request.user, pk=pk)
    if request.method == 'POST':
        form = ComputeForm(request.POST, instance=compute)
        if form.is_valid():
            compute = form.save(commit=False)
            compute.user = request.user
            compute.save()
        return redirect('/compute')
    else:
        form = ComputeForm(instance=compute)
    return render(request, 'compute-update.html', {'form': form, 'id': pk})

@login_required
def compute_delete(request, pk):
    compute = get_object_or_404(Compute, user=request.user, pk=pk)
    data = dict()
    if request.method == 'POST':
        compute.delete()
        data['form_is_valid'] = True
        resources = request.user.resources.all()
        data['html_resources_list'] = render_to_string('clouds-list.html', {'resources': resources})
    else:
        context = {'resource': compute}
        data['html_form'] = render_to_string('compute-delete.html', context, request=request)
    return JsonResponse(data)

frontend/views/storage.py
import logging

from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required

from frontend.forms import StorageForm
from frontend.models import Storage

# Get an instance of a logger
logger = logging.getLogger(__name__)

@login_required
def storage(request):
    storage_list = request.user.storage_systems.all()
    return render(request, 'storage.html', {'storage': storage_list})

def save_storage_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            storage = form.save(commit=False)
            storage.user = request.user
            storage.save()
            data['form_is_valid'] = True
            storage_list = request.user.storage_systems.all()
            data['html_storage_list'] = render_to_string('storage-list.html', {'storage': storage_list})
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)

@login_required
def storage_add(request):
    if request.method == 'POST':
        form = StorageForm(request.POST)
        if form.is_valid():
            storage = form.save(commit=False)
            storage.user = request.user
            storage.save()
        return redirect('/storage')
    else:
        form = StorageForm()

    return render(request, 'storage-add.html', {'form': form})

@login_required
def storage_update(request, pk):
    storage = get_object_or_404(Storage, user=request.user, pk=pk)
    if request.method == 'POST':
        form = StorageForm(request.POST, instance=storage)
        if form.is_valid():
            storage = form.save(commit=False)
            storage.user = request.user
            storage.save()
        return redirect('/storage')
    else:
        form = StorageForm(instance=storage)
    return render(request, 'storage-update.html', {'form': form, 'id': pk})

@login_required
def storage_delete(request, pk):
    storage = get_object_or_404(Storage, user=request.user, pk=pk)
    data = dict()
    if request.method == 'POST':
        storage.delete()
        data['form_is_valid'] = True
        storage_list = request.user.storage_systems.all()
        data['html_storage_list'] = render_to_string('storage-list.html', {'storage': storage_list})
    else:
        context = {'storage': storage}
        data['html_form'] = render_to_string('storage-delete.html', context, request=request)
    return JsonResponse(data)

templates/clouds.html
{% extends 'user-base.html' %}

{% load static %}

{% block title %}
  Compute
{% endblock %}

{% block javascript %}
<script src="{% static 'js/compute.js' %}"></script>
<script>
$(document).ready(function() {
        $('#compute-table').DataTable({
order: [[0, 'asc']],
"columnDefs": [
    { "orderable": false, "targets": [2] },
  ],    
"language": {
      "emptyTable": "No resources"
    },  
"bPaginate": true,
    "bLengthChange": false,
    "bFilter": false,
    "bInfo": true,
    "bAutoWidth": false
        });
} );
</script>
<script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
});
</script>
{% endblock %}

{% block contentuser %}
<h2 style="display: inline">Compute</h2>
&nbsp; &nbsp; &nbsp; &nbsp;
<h6 style="display: inline"> <a href="{% url 'compute_add' %}">
<span class="fa fa-plus"></span>
ADD RESOURCE
</a></h6>

          <br/>
          <br/>

  <table class="table table-striped" id="compute-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Type</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% include 'clouds-list.html' %}
    </tbody>
  </table>

  <div class="modal fade" id="modal-compute">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>      
    </div>
  </div>

{% endblock %}

templates/compute-update.html
{% extends 'user-base.html' %}
{% load static %}
{% block title %}
Update resource
{% endblock %}
{% block javascript %}
<script src="{% static 'js/compute.js' %}"></script>
{% endblock %}
{% block contentuser %}
<h2><a href="/compute"><i class="feather-32" data-feather="arrow-left"></i></a> Update resource</h2>
<br/>
<form method="post" action="{% url 'compute_update' id %}">
  {% csrf_token %}
<div class="container">
  {% include 'compute-form.html' %}
  <button type="submit" class="btn btn-primary">Update</button>
<a class="btn btn-outline-dark" href="/compute">Cancel</a>
</div>
</form>
<br/>
{% endblock %}

templates/create-token.html
<div class="modal fade" id="create-token" tabindex="-1" role="dialog" aria-labelledby="createTokenLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="createTokenLabel">API token</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      Your token is:
      <div class="replace">
      </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

templates/create_token_content.html
<div class="modal-body">
  Your token is: {{ token }}
</div>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load socialaccount %}

{% block title %}
  Submit Globally, Run Globally
{% endblock %}

{% block javascript %}
<script>
function setCookie(name,value,days) {
    var expires = "";
    if (days) {
        var date = new Date();
        date.setTime(date.getTime() + (days*24*60*60*1000));
        expires = "; expires=" + date.toUTCString();
    }
    document.cookie = name + "=" + (value || "")  + expires + "; path=/";
}
function getCookie(name) {
    var nameEQ = name + "=";
    var ca = document.cookie.split(';');
    for(var i=0;i < ca.length;i++) {
        var c = ca[i];
        while (c.charAt(0)==' ') c = c.substring(1,c.length);
        if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
    }
    return null;
}

function eraseCookie(name) {   
    document.cookie = name +'=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;';
}

function cookieConsent() {
    if (!getCookie('allowCookies')) {
        $('.toast').toast('show')
    }
}

$('#btnAccept').click(()=>{
    setCookie('allowCookies','1',7)
    $('.toast').toast('hide')
})

// load
cookieConsent()

</script>
{% endblock %}
  
{% block content %}
      <section id="promo">
      <nav class="navbar navbar-dark navbar-expand">
          <div class="navbar-brand-public mb-0">prominence</div>
          <div class="navbar-collapse collapse">
           <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link-public" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link-public" href="https://prominence.readthedocs.io">Docs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link-public" href="https://github.com/prominence-eosc/">GitHub</a>
          </li>
           </ul>
           </div>
      </nav>
         <div style="background:transparent !important" class="jumbotron align-items-center pt-5">
            <div class="container">
               <div class="row">
                  <div class="col">
                     <div class="display-4 text-center text-md-left text-light" style="font-weight:200">
                        High throughput and high performance computing without servers or clusters
                     </div>
                     <h4 class="text-center text-md-left text-light mb-6 mb-lg-8" style="font-weight:100">
                        Run containerised jobs across many clouds without managing infrastructure.
                     </h4>
		     <br/>
		  <h6>
		  <a class="btn btn-light nav-link w-25" href="{% provider_login_url 'egicheckin' %}">Login with EGI Check-in</a>
		  </h6>
                  </div>

               </div>
            </div>
         </div>
      </section>

      <div class="jumbotron">
      <h2 class="text-center">Overview</h2>
      <div class="container">
	      <div class="row justify-content-md-center">
	      <div class="col-sm-8">
		      <h6 class="text-center">Prominence is a platform which allows users to easily exploit idle cloud resources for running scientific workloads. By default resources from the <a href="https://www.egi.eu/services/cloud-compute/">EGI Cloud Compute</a> service are used.</h6>
      </div>
      </div>
      </div>
      </div>

      <br/>
      <br/>
      <br/>

      <div class="container">
         <div class="row">
		 <div class="col">
		 <h2 class="text-center">Features</h2>
		 </div>
	 </div>
         <div class="row">
            <div class="col">
               <i class="feather-large" data-feather="user"></i>
	       <br/><br/>
               <h4 class="display-6 text-center text-md-left" style="font-weight:300">
                  Run jobs from anywhere
               </h4>
               <p class="text-muted">
                  Manage jobs using a web UI, a simple batch system style command line interface or interact programmatically using a RESTful API.
               </p>
            </div>
            <div class="col">
               <i class="feather-large" data-feather="codesandbox"></i>
	       <br/><br/>
               <h4 class="display-6 text-center text-md-left" style="font-weight:300">
                  Reliability & reproduceability
               </h4>
               <p class="text-muted">
                  All jobs are run in containers to ensure they will run reliably anywhere and are reproducible.
               </p>
            </div>
            <div class="col">
               <i class="feather-large" data-feather="server"></i>
	       <br/><br/>
               <h4 class="display-6 text-center text-md-left" style="font-weight:300">
                  Invisible infrastructure
               </h4>
               <p class="text-muted">
                  All infrastructure provisioning is handled completely automatically and is totally invisible to the user.
               </p>
            </div>
         </div>
         <br/>
         <br/>
         <div class="row">
            <div class="col">
               <i class="feather-large" data-feather="grid"></i>
	       <br/><br/>
               <h4 class="display-6 text-center text-md-left" style="font-weight:300">
                  MPI ready
               </h4>
               <p class="text-muted">
                  Run multi-node Open MPI, Intel MPI or MPICH jobs in addition to single-node jobs.
               </p>
            </div>
            <div class="col">
               <i class="feather-large" data-feather="copy"></i>
	       <br/><br/>
               <h4 class="display-6 text-center text-md-left" style="font-weight:300">
                  Workflows
               </h4>
               <p class="text-muted">
                  Construct complex workflows by specifying the dependencies between different jobs.
               </p>
            </div>
            <div class="col">
               <i class="feather-large" data-feather="database"></i>
	       <br/><br/>
               <h4 class="display-6 text-center text-md-left" style="font-weight:300">
                  Data access
               </h4>
               <p class="text-muted">
		  Jobs can access data transparently from OneData, WebDAV or object storage.
               </p>
            </div>
         </div>
      </div>

      <br/>
      <br/>
      <br/>

      <div class="jumbotron" style="background-color:#666666">
      <h2 class="text-center text-white">Scale from zero and back again</h2>
      <div class="container">
              <div class="row justify-content-md-center">
              <div class="col-sm-8">
                      <h6 class="text-center text-white">Resources are only used when they are needed to run workloads.</h6>
      </div>
      </div>
      </div>
      </div>

      <br/>
      <br/>
      <br/>    


      <div class="container">
	      <h2 class="text-center">Submit globally, run globally</h2>
	      <h6 class="text-center">Submit from anywhere, run on any cloud.</h6>
	      <br/>
              <div class="row justify-content-md-center">
		      <img src="{% static 'images/prominence.png' %}" alt="PROMINENCE enables users to submit jobs using a web UI, command line interface, REST API or Jupyter, and run jobs across local, national, and public clouds and the EGI Federated Cloud."></img>
      </div>
      </div>



      <br/>       
      <br/>       


  <footer class="footer">
    <div class="container">
        <a class="text-light" href="/terms-of-use">Terms of use</a> | <a class="text-light" href="/privacy-policy">Privacy policy</a>
    </div>     
  </footer>

<div class="fixed-bottom p-4">
    <div class="toast bg-dark text-white w-100 mw-100" role="alert" data-autohide="false">
        <div class="toast-body p-4 d-flex flex-column">
            <h4>This site uses cookies</h4>
            <p>
	    We use cookies to ensure you get the best experience on our website. <a href="https://www.cookiesandyou.com">Learn more</a>
            </p>
            <div class="ml-auto">
                <button type="button" class="btn btn-light" id="btnAccept">
                    Accept
                </button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/job_delete.html
<form method="post" action="{% url 'job_delete' job.id %}" class="js-job-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <h5 class="modal-title">Confirm job deletion</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete job <strong>{{ job.id }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete</button>
  </div>
</form>

templates/job_describe.html
<form method="post" action="" class="js-job-describe-form">
  {% csrf_token %}
  <div class="modal-header">
    <h5 class="modal-title">Job</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    {% include job_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Close</button>
  </div>
</form>

templates/jobs_list.html
{% for job in job_list %}
  <tr>
    <td>{{ job.id }}</td>
    <td>{{ job.name }}</td>
    <td>
      {% if job.status == "running" %}
        <span class="badge badge-success">Running</span>
      {% elif job.status == "failed" %}
        <span class="badge badge-danger">Failed</span>
      {% elif job.status == "deleted" %}
        <span class="badge badge-warning">Deleted</span>
      {% elif job.status == "pending" %}
        <span class="badge badge-info">Pending</span>
      {% elif job.status == "completed" %}
        <span class="badge badge-dark">Completed</span>
      {% endif %}
    </td>
    <td>{{ job.events.createTime }}</td>
    <td>
    {% if job.status != "pending" %}
      {{ job.elapsedTime }}
    {% endif %}
    </td>
    {% for task in job.tasks %}
    <td>{{ task.image }}</td>
    <td>{{ task.cmd }}</td>
    {% endfor %}
    <td style="width: 200px">
      <button type="button"
              class="btn btn-primary btn-sm js-describe-job"
	      data-url="{% url 'job_describe' job.id %}">
      <span class="fa fa-info"></span>
      </button>
      <button type="button"
              class="btn btn-danger btn-sm js-delete-job"
	      data-url="{% url 'job_delete' job.id %}">
        <span class="fa fa-trash"></span>
      </button>
    </td>
  </tr>
{% empty %}
  <tr>
    <td colspan="7" class="text-center">No jobs</td>
  </tr>
{% endfor %}

templates/storage-form.html
{% load widget_tweaks %}
  
{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %}

templates/storage_add.html
<form method="post" action="{% url 'storage_add' %}" class="js-storage-add-form">
  {% csrf_token %}
  <div class="modal-header">
    <h5 class="modal-title">Add a new storage system</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="modal-body">
    {% include 'storage_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-outline-dark" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Add</button>
  </div>
</form>

templates/storage_list.html
{% for storage_system in storage %}
  <tr>
    <td>{{ storage_system.name }}</td>
    <td>{{ storage_system.get_storage_type_display }}</td>
    <td>{{ storage_system.hostname }}</td>
    <td style="width: 200px">
      <button type="button"
              class="btn btn-warning btn-sm js-update-storage"
              data-url="{% url 'storage_update' storage_system.id %}">
        <span class="fa fa-pencil"></span> Edit
      </button>
      <button type="button"
              class="btn btn-danger btn-sm js-delete-storage"
              data-url="{% url 'storage_delete' storage_system.id %}">
        <span class="fa fa-trash"></span> Delete
      </button>
    </td>
  </tr>
{% empty %}
  <tr>
    <td colspan="7" class="text-center">No storage defined</td>
  </tr>
{% endfor %}    

templates/workflow_list.html
  <tr>
    <td colspan="7" class="text-center">No workflows</td>
  </tr>